### ISSUE TITLE
Odd domain name list in blocklist.txt

### ISSUE THREAD

**Issue by Tntdruid** [eLVee1991/youtubeblock#1]
See load of this:

r2.sn-5hne6nsk.googlevide
 r5---sn-5hne6nsd.googlevi
 r4.sn-5hne6nlk.googlevide
 r5---sn-5hnedn7s.googlevideo
 r5.sn-5hnedn7s.googlevide
 r5---sn-5hne6nsd.googlevideo
 r5.sn-5hne6nsd.googlevide
 r5---sn-5hne6n7e.googlevi
 r2.sn-un57en7l.googlevide
--sn-5hne6nsy.googlevideo.com fr
 r2---sn-un57en7l.googlevi
 r5---sn-5hnedn7s.googlevi
 r4.sn-h5q7dnlk.googlevide
 r4---sn-5hnekn76.googlevideo
 r6---sn-5hnedn7s.googlevideo
 r6.sn-5hnedn7s.googlevide
 r6.sn-5hnednlk.googlevide
 r5---sn-5hne6n7e.googlevideo
 r2---sn-un57en7l.googlevideo
 r1---sn-p5qlsns6.googlevi
 r4---sn-5hne6ns6.googlevideo
 r4.sn-5hne6ns6.googlevide
 r2---sn-5hne6nsk.googlevi
 r3---sn-5hne6nlr.googlevi
 r4---sn-5hne6ns6.googlevi
 r3---sn-5hne6nsk.googlevideo
 r1.sn-p5qlsns6.googlevide
 r1.sn-5hnekn7z.googlevide
 r3.sn-5hne6nsk.googlevide
 r6---sn-5hnedn7s.googlevi
 r4---sn-h5q7dnlk.googlevideo
 r4---sn-5hnekn76.googlevi
 r2---sn-5hnednlk.googlevi
 r6---sn-5hnednlk.googlevi
 r3---sn-5hne6nlr.googlevideo
r1.sn-5hne6nsy.googlevideo.com f
 r3.sn-5hne6nlr.googlevide
 r4.sn-5hnekn76.googlevide
 r4---sn-h5q7dnlk.googlevi
 r1---sn-f5f7ln7s.googlevi
 r1---sn-5hnekn76.googlevi
 r1---sn-5hnekn76.googlevideo
 r4---sn-5hne6nlk.googlevi
 r3---sn-5hne6nsk.googlevi
 r1---sn-p5qlsns6.googlevideo
 r1---sn-f5f7ln7s.googlevideo
r1---sn-5hne6nsy.googlevideo.com
 r4---sn-5hne6nlk.googlevideo
 r2.sn-5hnednlk.googlevide
 r1.sn-5hnekn76.googlevide
 r1---sn-5hnekn7z.googlevi
 r5.sn-5hne6n7e.googlevide
 r2---sn-5hne6nsk.googlevideo
 r1---sn-5hnekn7z.googlevideo
 r6---sn-5hnednlk.googlevideo
 r2---sn-5hnednlk.googlevideo

**Comment by eLVee1991** [comment]
I'll check it out this weekend. Haven't happened to me yet. I'll play around the sorting.

**Comment by Tntdruid** [comment]
Thanks, have a great weekend 😄

**Comment by volpeandrew** [comment]
Python requires you to get the indents right which can be confusing. I made a fork with the changes here, you can just grab the whole file: https://github.com/volpeandrew/youtubeblock/blob/master/youtubeblock.py

**Comment by Tntdruid** [comment]
Thanks

**Comment by eLVee1991** [comment]
The problem should be fixed in the newly uploaded code.

**Comment by Tntdruid** [comment]
Still getting:

r1---sn-5hne6n7e.googlev
r1---sn-5hne6n7e.googlevide
r1---sn-5hne6n7l.googlevi
r1---sn-5hne6n7l.googlevideo
r1---sn-5hne6n7s.googlevide
r1---sn-5hne6n7s.googlevideo.c
r1---sn-5hne6nlk.googlevi
r1---sn-5hne6nlk.googlevideo
r1---sn-5hne6nlk.googlevideo.com
r1---sn-5hne6nlr.googlevi
r1---sn-5hne6nlr.googlevideo
r1---sn-5hne6ns6.googlevi
r1---sn-5hne6ns6.googlevideo.com
r1---sn-5hne6nsy.googlev
r1---sn-5hne6nsy.googlevide
r1---sn-5hne6nsz.googlevi
r1---sn-5hne6nsz.googlevideo
r1---sn-5hnedn7l.googlevideo.com
r1---sn-5hnedn7s.googlevi
r1---sn-5hnedn7s.googlevideo
r1---sn-5hnednlk.googlevideo.com
r1---sn-5hnednlr.googlevi
r1---sn-5hnednlr.googlevideo

**Comment by eLVee1991** [comment]
Can you empty the blocklist and try again?

**Comment by Tntdruid** [comment]
Did that, now i get

[+] Checking all dns requests for YouTube queries.
[+] Checking for youtube fingerprint..
[+] Done checking requests.
[+] Sorting urls..
[+] Done sorting urls for queries.
[+] Sorting for unique urls and adding to list 'blocklist.txt'..
[+] Done adding to blocklist.
[+] Adding contents of blocklist to pihole.
  [i] Adding from to blacklist...
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!
  [i] from already exists in blacklist, no need to add!
  [i] from does not exist in whitelist, no need to remove!

  [i] Using cached Event Horizon list...
  [i] 616872 unique domains trapped in the Event Horizon
  [i] Number of blacklisted domains: 135
  [i] Number of regex filters: 0
  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter

  [✓] Force-reloading DNS service
  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled
[+] Done adding to pihole.
[+] Finished.

**Comment by eLVee1991** [comment]
This means the domains in the blocklist (most of them) are already added to the pihole blacklist. 
This is how the scripts works for now. I'm currently working on a fix that will take care of domains that are already added to the pihole.

**Comment by Tntdruid** [comment]
Get the same on my test pihole, never used the script there before

**Comment by eLVee1991** [comment]
Can you try again now?

**Comment by eLVee1991** [comment]
Less or still the same amount?

**Comment by Tntdruid** [comment]
same amount as before

**Comment by eLVee1991** [comment]
I added a check to see if it is already added to the pihole. Can you try again now?

**Comment by eLVee1991** [comment]
It seems to be running smoothly from my part now.

**Comment by Tntdruid** [comment]
Works so far, will do some more testing

**Comment by eLVee1991** [comment]
Thanks a lot. Let me know if you run into any problems.
